// samples/react/00 SimpleForm/src/components/common/input.tsx
import * as React from 'react';

interface Props {
  name: string;
  label: string;
  onChange: any;
  placeholder?: string;
  value: string;
  error: string;
}

export class Input extends React.Component<Props, {}> {
  render() {
    let wrapperClass = 'form-group';
    if (this.props.error && this.props.error.length > 0) {
      wrapperClass = '${wrapperClass} has-error';
    }

    return (
      <div className={wrapperClass}>
        <label htmlFor={this.props.name}>{this.props.label}</label>
        <div className="field">
          <input type="text"
            id={this.props.name}
            name={this.props.name}
            className="form-control"
            placeholder={this.props.placeholder}
            ref={this.props.name}
            value={this.props.value}
            onChange={this.props.onChange} />
          <div className="help-block">{this.props.error}</div>
        </div>
      </div>
    );
  }
}

// samples/vuejs/typescript/00 Custom Validator/src/common/components/form/input.tsx
import Vue, {ComponentOptions} from 'vue';

interface Props extends Vue {
  className: string;
  placeholder: string;
  type: string;
  value: any;
  inputHandler: (event) => void;
  label: string;
  name: string;
}

export const InputComponent = Vue.extend({
  props: [
    'className',
    'placeholder',
    'type',
    'value',
    'inputHandler',
    'label',
    'name',
  ],
  render: function(h) {
    return (
      <div class={`form-group ${this.className}`}>
        <label for={this.name}>
          {this.label}
        </label>
        <input
          class="form-control"
          name={this.name}
          placeholder={this.placeholder}
          type={this.type}
          value={this.value}
          onInput={this.inputHandler}
        />
      </div>
    );
  },
} as ComponentOptions<Props>);
